[package]
name = "t3zla/classbasedfighter"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@1.2.1"
Component = "sleitnick/component@2.4.6"
Timer = "sleitnick/timer@1.1.2"
Trove = "sleitnick/trove@0.5.0"
Input = "sleitnick/input@2.1.1"
Knit = "sleitnick/knit@^1.4"